Implementa a sessão
nodebr/nodebr pull request #70
Opened 2016-11-15 21:09 UTC by alanhoff

2016-11-15 21:09 UTC, alanhoff commented
@thebergamo RFR

2016-11-15 22:47 UTC, brunops commented on circle.yml
> +    COOKIE_SECRET: here_be_dragrons
dragrons?

2016-11-15 23:45 UTC, brunops reviewed
minor comments, pretty good overall 👍

2016-11-15 23:45 UTC, brunops commented on lib/session.js
> +    maxAge: 168 * 60 * 60 * 1000, //  Uma semana
Não seria mais claro `24 * 7` ao invés de `168`? (mas na real não ligo muito pra isso)

2016-11-15 23:45 UTC, brunops commented on lib/session.js
> +        res.status(401).send({ error: 'Unauthorized' })
Dá pra remover o `else` se adicionar um `return` aqui

2016-11-15 23:45 UTC, brunops commented on resources/sessions/handlers.js
> +    req.session.user_id = user.id
camelCase? userId?

2016-11-15 23:45 UTC, brunops commented on test/fixtures/sessions.js
> +.then(res => {
se quiser ser fancy `res => res.header['set-cookie'].map(e => e.split(';')[0]).join(';')`

2016-11-16 00:24 UTC, thebergamo requested changes

2016-11-16 00:24 UTC, thebergamo commented on lib/error-handler.js
> +    res.status(err.output.statusCode).send(err.output.payload)
Use um return aqui no lugar do else. Nos casos acima também acredito que isso ira facilitar a leitura.

2016-11-16 00:24 UTC, thebergamo commented on lib/session.js
> +    maxAge: 168 * 60 * 60 * 1000, //  Uma semana
Concordo com o @brunops se ficar `24 * 7` facilita a leitura

2016-11-16 00:24 UTC, thebergamo commented on package.json
> +    "reset": "node -e \"require('./lib/db').dropDatabase().then(() => process.exit(0), err => { console.error(err.stack); process.exit(1) })\"; npm run migrate"
Acredito que valha a pena mover isso para um arquivo e referenciar o mesmo aqui? Talvez criar um diretório `scripts` o mesmo acredito que valha pro `test-cov`

2016-11-16 00:24 UTC, thebergamo commented on resources/sessions/handlers.js
> +    req.session.user_id = user.id
No caso, quando são objetos é melhor usar com o `_` mesmo @brunops

2016-11-16 00:24 UTC, thebergamo commented on resources/sessions/handlers.js
> +    throw Boom.badData('Sua senha está incorreta')
Acho que faz mais sentido checar se não tem password e devolver um throw. Dai estar a sessão caso tudo esteja correto e seguir a vida.

2016-11-16 01:07 UTC, alanhoff commented on circle.yml
> +    COOKIE_SECRET: here_be_dragrons
Frixed

![](https://cdn.meme.am/instances/400x400/22673686.jpg)

2016-11-16 01:08 UTC, alanhoff commented on lib/session.js
> +    maxAge: 168 * 60 * 60 * 1000, //  Uma semana
Fixed, mas botei o dia na frente das horas :-)

2016-11-16 01:08 UTC, alanhoff commented on lib/session.js
> +        res.status(401).send({ error: 'Unauthorized' })
Fixed

2016-11-16 01:10 UTC, alanhoff commented on resources/sessions/handlers.js
> +    req.session.user_id = user.id
Quando alguma referência a uma coluna no banco de dados aí usa underscore, caso contrário camelCase mesmo.

2016-11-16 01:10 UTC, alanhoff commented on test/fixtures/sessions.js
> +.then(res => {
Fixed

2016-11-16 01:11 UTC, alanhoff commented on lib/error-handler.js
> +    res.status(err.output.statusCode).send(err.output.payload)
Fixed

2016-11-16 01:14 UTC, alanhoff commented on package.json
> +    "reset": "node -e \"require('./lib/db').dropDatabase().then(() => process.exit(0), err => { console.error(err.stack); process.exit(1) })\"; npm run migrate"
Fixed. Não acho que o `test-cov` deva ir para um script visto que é um punhado de argumentos, sem lógica de programação !== script.

2016-11-16 01:14 UTC, alanhoff commented on resources/sessions/handlers.js
> +    throw Boom.badData('Sua senha está incorreta')
@thebergamo não entendi

2016-11-16 01:18 UTC, thebergamo commented on resources/sessions/handlers.js
> +    throw Boom.badData('Sua senha está incorreta')
```
if (!yeld user.compare(req.body.password)) {
    throw Boom.badData('Sua senha está incorreta')
}
```

Tipo isso ^

2016-11-16 01:21 UTC, alanhoff commented
@thebergamo RFR

2016-11-16 01:34 UTC, merged

2016-11-16 01:53 UTC, brunops commented on lib/session.js
> +    maxAge: 168 * 60 * 60 * 1000, //  Uma semana
radical